// examples/with-svelte/src/pages/home/index.svelte
<script>
  import * as yup from 'yup';
  import AgeInput from 'src/pages/home/age-input.svelte';
  import NameInput from 'src/pages/home/name-input.svelte';
  import AgeListener from 'src/pages/home/age-listener.svelte';
  import {setFfwContext, initFFw, prepareYup} from 'ffw-svelte';

  const ffw = initFFw({
    initValues: {
      age: 42,
      name: 'Robbin',
    },
    validateSchema: prepareYup({
      age: yup.number().required(),
      name: yup.string().required(),
    }),
  });
  globalThis.form = ffw;

  setFfwContext(ffw);
  const valid = ffw.s.valid;
</script>

{#if $valid}
  valid
{/if}
{#if !$valid}
  invalid
{/if}

<AgeInput />
<AgeListener />
<NameInput />

// examples/with-react/src/routes/home/index.jsx
import {useInitForm, FfwProvider, prepareYup} from 'ffw-react';
import AgeInput from './age-input';
import AgeListener from './age-listener';
import FormValid from './form-valid';
import GlobalListener from './global-listener';
import NameInput from './name-input';
import * as yup from 'yup';

function Home() {
  const form = useInitForm({
    initValues: {
      name: 'aleks',
      age: 42,
    },
    validateSchema: prepareYup({
      age: yup.number().required(),
    }),
  });

  globalThis.form = form;
  return (
    <FfwProvider value={form}>
      <div>
        <AgeInput />
        <AgeListener />
        <GlobalListener />
        <NameInput />
        <FormValid />
        <div
          onClick={() => {
            form.f.name.set('1');
            form.f.age.set('2');
          }}
        >
          click
        </div>
      </div>
    </FfwProvider>
  );
}

export default Home;
