// examples/with-react/src/routes/home/index.tsx
import {useInitFfw, FfwProvider} from 'ffw';
import AgeInput from 'src/routes/home/age-input';
import AgeListener from 'src/routes/home/age-listener';
import GlobalListener from 'src/routes/home/global-listener';
import NameInput from 'src/routes/home/name-input';

function Home() {
  const ffw = useInitFfw({
    initValues: {
      name: 'aleks',
      age: 42,
    },
  });
  globalThis.form = ffw;
  return (
    <FfwProvider value={ffw}>
      <div>
        <AgeInput />
        <AgeListener />
        <GlobalListener />
        <NameInput />
      </div>
    </FfwProvider>
  );
}

export default Home;

// examples/with-svelte/src/pages/home/index.svelte
<script lang="ts">
  import * as yup from 'yup'
  import AgeInput from 'src/pages/home/age-input.svelte';
  import NameInput from 'src/pages/home/name-input.svelte';
  import AgeListener from 'src/pages/home/age-listener.svelte';
  import {setFfwContext, initFFw} from 'ffw-s'
  const ffw = initFFw({
    initValues: {
      age: 42,
      name: "Robbin"
    },
    validateSchema: yup.object({
      age: yup.number().required(),
      name: yup.string().required()
    }),
  })
  globalThis.form = ffw

  setFfwContext(ffw)
  //
</script>

<AgeInput/>
<AgeListener/>
<NameInput/>
