// examples/with-svelte/src/pages/home/index.svelte
<script>
  import * as yup from 'yup';
  import AgeInput from 'src/pages/home/age-input.svelte';
  import NameInput from 'src/pages/home/name-input.svelte';
  import AgeListener from 'src/pages/home/age-listener.svelte';
  import {setFfwContext, initFFw, prepareYup} from 'ffw-svelte';

  const ffw = initFFw({
    initValues: {
      age: 42,
      name: 'Robbin',
    },
    validateSchema: prepareYup({
      age: yup.number().required(),
      name: yup.string().required(),
    }),
  });
  globalThis.form = ffw;

  setFfwContext(ffw);
  const valid = ffw.s.valid;
</script>

{#if $valid}
  valid
{/if}
{#if !$valid}
  invalid
{/if}

<AgeInput />
<AgeListener />
<NameInput />

// examples/with-solid/routes/home/home.jsx
import {initForm, FfwContextProvider} from 'ffw-solid';
import AgeInput from './age-input.jsx';
import AgeListener from './age-listener.jsx';
import FormValid from './form-valid.jsx';
import NameInput from './name-input.jsx';
import NameListener from './name-listener.jsx';
import {prepareYup} from 'ffw-solid';
import * as yup from 'yup';

function Home() {
  const form = initForm({
    initValues: {
      age: 42,
      name: 'Aleksey',
    },
    validateSchema: prepareYup({
      age: yup.number().required(),
      name: yup.string().required(),
    }),
  });
  globalThis.form = form;
  return (
    <FfwContextProvider value={form}>
      <div>
        <AgeInput />
        <AgeListener />
        <NameInput />
        <NameListener />
        <FormValid />
      </div>
    </FfwContextProvider>
  );
}

export default Home;
